"""Initial schema with all models

Revision ID: 281a758e69ec
Revises: 
Create Date: 2026-01-12 03:13:29.959560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281a758e69ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('actor_type', sa.Enum('AGENCY', 'OFFICIAL', 'CONTRACTOR', 'ENTITY', 'FOREIGN_GOVERNMENT', name='actortypeenum'), nullable=False),
    sa.Column('parent_actor_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wikipedia_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_actor_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actors_actor_type'), 'actors', ['actor_type'], unique=False)
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('legal_frameworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('framework_type', sa.Enum('CONSTITUTIONAL', 'STATUTORY', 'TREATY', 'COURT_ORDER', 'REGULATION', name='legalframeworktypeenum'), nullable=False),
    sa.Column('citation', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_frameworks_framework_type'), 'legal_frameworks', ['framework_type'], unique=False)
    op.create_index(op.f('ix_legal_frameworks_name'), 'legal_frameworks', ['name'], unique=True)
    op.create_table('patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('historical_precedent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_name'), 'patterns', ['name'], unique=True)
    op.create_table('targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_name'), 'targets', ['name'], unique=True)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING_REVIEW', 'DISPUTED', 'DOCUMENTED', 'ADJUDICATED', name='verificationstatusenum'), nullable=False),
    sa.Column('geographic_scope', sa.Enum('LOCAL', 'STATE', 'FEDERAL', 'INTERNATIONAL', name='geographicscopeenum'), nullable=False),
    sa.Column('location_state', sa.String(length=100), nullable=True),
    sa.Column('location_city', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_category_id'), 'incidents', ['category_id'], unique=False)
    op.create_index(op.f('ix_incidents_date_occurred'), 'incidents', ['date_occurred'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_verification_status'), 'incidents', ['verification_status'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('current_title', sa.String(length=200), nullable=True),
    sa.Column('agency_id', sa.String(), nullable=True),
    sa.Column('biography_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['actors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_table('incident_actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PERPETRATOR', 'COMPLICIT', 'RESISTOR', 'WHISTLEBLOWER', name='actorroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'actor_id', name='uix_incident_actor')
    )
    op.create_index(op.f('ix_incident_actors_actor_id'), 'incident_actors', ['actor_id'], unique=False)
    op.create_index(op.f('ix_incident_actors_incident_id'), 'incident_actors', ['incident_id'], unique=False)
    op.create_table('incident_legal_frameworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('legal_framework_id', sa.String(), nullable=False),
    sa.Column('violation_type', sa.Enum('ALLEGED', 'DOCUMENTED', 'ADJUDICATED', name='violationtypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legal_framework_id'], ['legal_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'legal_framework_id', name='uix_incident_legal_framework')
    )
    op.create_index(op.f('ix_incident_legal_frameworks_incident_id'), 'incident_legal_frameworks', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_legal_frameworks_legal_framework_id'), 'incident_legal_frameworks', ['legal_framework_id'], unique=False)
    op.create_table('incident_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'pattern_id', name='uix_incident_pattern')
    )
    op.create_index(op.f('ix_incident_patterns_incident_id'), 'incident_patterns', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_patterns_pattern_id'), 'incident_patterns', ['pattern_id'], unique=False)
    op.create_table('incident_persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ORDERED', 'EXECUTED', 'RESISTED', 'EXPOSED', name='personroleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'person_id', name='uix_incident_person')
    )
    op.create_index(op.f('ix_incident_persons_incident_id'), 'incident_persons', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_persons_person_id'), 'incident_persons', ['person_id'], unique=False)
    op.create_table('incident_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'target_id', name='uix_incident_target')
    )
    op.create_index(op.f('ix_incident_targets_incident_id'), 'incident_targets', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_targets_target_id'), 'incident_targets', ['target_id'], unique=False)
    op.create_table('ingestion_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_EDIT', name='ingestionstatusenum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_incident_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_queue_status'), 'ingestion_queue', ['status'], unique=False)
    op.create_table('related_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('related_incident_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PRECEDED_BY', 'FOLLOWED_BY', 'RELATED', 'ESCALATION_OF', 'RESPONSE_TO', name='relationshiptypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'related_incident_id', name='uix_related_incidents')
    )
    op.create_index(op.f('ix_related_incidents_incident_id'), 'related_incidents', ['incident_id'], unique=False)
    op.create_index(op.f('ix_related_incidents_related_incident_id'), 'related_incidents', ['related_incident_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.Enum('COURT_FILING', 'GOVERNMENT_REPORT', 'FOIA', 'NEWS_PRIMARY', 'NEWS_SECONDARY', 'ACADEMIC', 'NGO_REPORT', 'FIRSTHAND_ACCOUNT', 'VIDEO', 'SOCIAL_MEDIA', 'LEAKED_DOCUMENT', name='sourcetypeenum'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('reliability', sa.Enum('PRIMARY', 'SECONDARY', 'TERTIARY', name='reliabilityenum'), nullable=False),
    sa.Column('archived_url', sa.String(length=1000), nullable=True),
    sa.Column('archived_locally', sa.Boolean(), nullable=False),
    sa.Column('local_file_path', sa.String(length=1000), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_incident_id'), 'sources', ['incident_id'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_incident_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_related_incidents_related_incident_id'), table_name='related_incidents')
    op.drop_index(op.f('ix_related_incidents_incident_id'), table_name='related_incidents')
    op.drop_table('related_incidents')
    op.drop_index(op.f('ix_ingestion_queue_status'), table_name='ingestion_queue')
    op.drop_table('ingestion_queue')
    op.drop_index(op.f('ix_incident_targets_target_id'), table_name='incident_targets')
    op.drop_index(op.f('ix_incident_targets_incident_id'), table_name='incident_targets')
    op.drop_table('incident_targets')
    op.drop_index(op.f('ix_incident_persons_person_id'), table_name='incident_persons')
    op.drop_index(op.f('ix_incident_persons_incident_id'), table_name='incident_persons')
    op.drop_table('incident_persons')
    op.drop_index(op.f('ix_incident_patterns_pattern_id'), table_name='incident_patterns')
    op.drop_index(op.f('ix_incident_patterns_incident_id'), table_name='incident_patterns')
    op.drop_table('incident_patterns')
    op.drop_index(op.f('ix_incident_legal_frameworks_legal_framework_id'), table_name='incident_legal_frameworks')
    op.drop_index(op.f('ix_incident_legal_frameworks_incident_id'), table_name='incident_legal_frameworks')
    op.drop_table('incident_legal_frameworks')
    op.drop_index(op.f('ix_incident_actors_incident_id'), table_name='incident_actors')
    op.drop_index(op.f('ix_incident_actors_actor_id'), table_name='incident_actors')
    op.drop_table('incident_actors')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_incidents_verification_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_date_occurred'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_category_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_targets_name'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_patterns_name'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_legal_frameworks_name'), table_name='legal_frameworks')
    op.drop_index(op.f('ix_legal_frameworks_framework_type'), table_name='legal_frameworks')
    op.drop_table('legal_frameworks')
    op.drop_table('categories')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    op.drop_index(op.f('ix_actors_actor_type'), table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
